GetVersion に対して SendVersion を返すようにした。
cheatank/server pull request #2
Opened 2021-12-06 10:32 UTC by cheichey

2021-12-06 10:43 UTC, sya-ri requested changes
PRありがとうございます。ざっと見た感じのレビューです。対応お願いします👊

2021-12-06 10:43 UTC, sya-ri commented on build.gradle.kts
> +    implementation("org.jetbrains.kotlin:kotlin-stdlib:1.6.0")
kotlin() を使って問題ないです。この変更は不要です

2021-12-06 10:43 UTC, sya-ri commented on build.gradle.kts
> +    testImplementation("org.jetbrains.kotlin:kotlin-test:1.6.0")
kotlin() を使ってください

2021-12-06 10:43 UTC, sya-ri commented on src/main/kotlin/com/github/cheatank/server/route/connectRoute.kt
> +                val rawPacket = Packet.fromByteArray(frame.readBytes())
common を最新版に変更して、ビルドし直してみてください。エラーが出ると思います。

rawPacket が RawPacket から RawPacket? に変更されました

2021-12-06 10:43 UTC, sya-ri commented on src/test/kotlin/WebSocketTest.kt
> +            }
Application#application を使えると思うので、それを使うようにしてください

2021-12-06 10:43 UTC, sya-ri commented on src/test/kotlin/WebSocketTest.kt
> +                outgoing.send(Frame.Binary(true, bytes))
object を一時変数に代入する必要は基本的にありません

2021-12-06 10:43 UTC, sya-ri commented on src/test/kotlin/WebSocketTest.kt
> +                assertIs<IntData>(packetData)
test/ に util パッケージを作成して、testPacketRespond のようなメソッドを作成してください。

送るパケットの指定や、戻ってきたパケットの型検知まで出来たらいいと思います

2021-12-06 10:43 UTC, sya-ri commented on src/test/kotlin/WebSocketTest.kt
> +        }
use を使うと close を書く必要が無くなると思います

2021-12-07 03:39 UTC, sya-ri requested changes
対応ありがとうございます。レビュー漏れあったので対応お願いします💪

2021-12-07 03:39 UTC, sya-ri commented on src/main/kotlin/com/github/cheatank/server/route/connectRoute.kt
> +                val rawPacket = Packet.fromByteArray(frame.readBytes()) ?: return
frame.readPacket() というメソッドを作ると綺麗になると思います

2021-12-07 03:39 UTC, sya-ri commented on src/test/kotlin/WebSocketTest.kt
> +                incoming, outgoing ->
incoming, outgoing -> は { の後に書いてほしいです

2021-12-07 07:19 UTC, sya-ri requested changes
対応お願いします😶‍🌫️

2021-12-07 07:19 UTC, sya-ri commented on build.gradle.kts
> +    testImplementation("io.ktor:ktor-server-test-host:1.6.6")
```suggestion
    implementation("com.github.cheatank:common:1.0.0-SNAPSHOT")
    implementation("io.ktor:ktor-server-core:1.6.6")
    implementation("io.ktor:ktor-server-cio:1.6.6")
    implementation("io.ktor:ktor-websockets:1.6.6")
    testImplementation(kotlin("test"))
    testImplementation("io.ktor:ktor-server-test-host:1.6.6")
```

test の依存関係は最後に書いた方がいいです

2021-12-07 07:19 UTC, sya-ri commented on src/main/kotlin/com/github/cheatank/server/route/connectRoute.kt
> +    for (frame in incoming) when (frame) {
{ は必ずつけてください

2021-12-07 07:19 UTC, sya-ri commented on src/main/kotlin/com/github/cheatank/server/route/connectRoute.kt
> +                processPacket(it)
そのような書き方をしたいのであれば、

```kotlin
frame.readPacket()?.let {
    processPacket(it)
} ?: return
```

と書いた方がいいです。また、return は不要でした(forしているので強制終了してしまう)

基本的に also を使わずに let を使いましょう。使い分けは以下の記事を見てみることをオススメします

https://qiita.com/ngsw_taro/items/d29e3080d9fc8a38691e

2021-12-08 00:21 UTC, sya-ri approved these changes
よさそうです！おつかれさまです

2021-12-08 00:22 UTC, cheichey commented
ありがとうございます。

2021-12-08 00:22 UTC, merged